# Project: plugin_test2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = dllmain.o plugindialog.o ../plugin_sdk/class.plugin.o $(RES)
LINKOBJ  = dllmain.o plugindialog.o ../plugin_sdk/class.plugin.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/dev/wx2.6.2/lib/gcc_dll" --no-export-all-symbols --add-stdcall-alias -mwindows  -mthreads  -lwxmsw26_core  -lwxbase26  -lkernel32  -luser32  -lgdi32  -lcomdlg32  -lwinspool  -lwinmm  -lshell32  -lcomctl32  -lole32  -loleaut32  -luuid  -lrpcrt4  -ladvapi32  -lwsock32  -lodbc32  -s 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/dev/wx2.6.2/lib/gcc_dll/msw"  -I"C:/dev/wx2.6.2/include"  -I"C:/dev/gpi/plugin_sdk" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/dev/wx2.6.2/lib/gcc_dll/msw"  -I"C:/dev/wx2.6.2/include"  -I"C:/dev/gpi/plugin_sdk" 
BIN  = ../plugin/output/plugins/plugin_test2.dll
CXXFLAGS = $(CXXINCS) -DBUILDING_DLL=1  -DWXUSINGDLL   -D__WXMSW__   -mthreads  -DNO_GCC_PRAGMA  -Wall  -fno-pcc-struct-return  -O3  -Os  -fno-rtti  -fno-exceptions     -fexpensive-optimizations -O3
CFLAGS = $(INCS) -DBUILDING_DLL=1   -fexpensive-optimizations -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../plugin/output/plugins/plugin_test2.dll all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

DLLWRAP=dllwrap.exe
DEFFILE=../plugin/output/plugins/libplugin_test2.def
STATICLIB=../plugin/output/plugins/libplugin_test2.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --driver-name c++ --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

dllmain.o: dllmain.cpp
	$(CPP) -c dllmain.cpp -o dllmain.o $(CXXFLAGS)

plugindialog.o: plugindialog.cpp
	$(CPP) -c plugindialog.cpp -o plugindialog.o $(CXXFLAGS)

../plugin_sdk/class.plugin.o: ../plugin_sdk/class.plugin.cpp
	$(CPP) -c ../plugin_sdk/class.plugin.cpp -o ../plugin_sdk/class.plugin.o $(CXXFLAGS)
